### ISSUE TITLE
Output不支持，你需要甄别一下是否是output

### ISSUE THREAD

**Issue by galaxy-sea** [RovingSea/utility-framework-springboot#9]
https://github.com/RovingSea/utility-framework-springboot/blob/d5e761fc98a316733366bc49eeea8745adb4d2c9/utility-spring-boot-core/src/main/java/io/github/rovingsea/utilityframework/core/response/ControllerResponseAdvice.java#L77

**Comment by RovingSea** [comment]
请问是这样吗？我测试了并没有问题
```java
@RestController
@RequestMapping("/stream")
public class StreamController {

    @RequestMapping("/print/{content}")
    public void upload(@PathVariable String content, HttpServletResponse response)throws IOException {
        ServletOutputStream outputStream = response.getOutputStream();
        outputStream.print(content);
    }

}
```

**Comment by RovingSea** [comment]
> https://github.com/RovingSea/utility-framework-springboot/blob/d5e761fc98a316733366bc49eeea8745adb4d2c9/utility-spring-boot-core/src/main/java/io/github/rovingsea/utilityframework/core/response/ControllerResponseAdvice.java#L77

请问是这样吗？我测试了并没有问题
```java
@RestController
@RequestMapping("/stream")
public class StreamController {

    @RequestMapping("/print/{content}")
    public void upload(@PathVariable String content, HttpServletResponse response)throws IOException {
        ServletOutputStream outputStream = response.getOutputStream();
        outputStream.print(content);
    }

}
```

**Comment by galaxy-sea** [comment]
```java
    @GetMapping
    public InputStreamResource download() throws IOException {
        return new InputStreamResource(new FileInputStream("/Users/changjinwei/Downloads/郭童童合集.txt"));
    }
```

**Comment by galaxy-sea** [comment]
溜了溜了, 你自己玩吧.

https://github.com/bes2008/agileway

**Comment by RovingSea** [comment]
> ```java
>    @GetMapping
>    public InputStreamResource download() throws IOException {
>        return new InputStreamResource(new FileInputStream("/Users/changjinwei/Downloads/郭童童合集.txt"));
>    }
> ```

Hello，我采取了兼容SpringMVC转换器的做法，根据转换器类型决定是否JSON化，你觉得这样可以吗？
https://github.com/RovingSea/utility-framework-springboot/commit/ac7d22235bc3a947b8af851ddf8796ac077467d0

**Comment by galaxy-sea** [comment]
请别再打开这个issue了!!! 

org.springframework.http.converter.HttpMessageConverter的各个子类难道都要在你的ControllerResponseAdvice类中写上一遍又一遍的if else么? 这让我觉得无聊, IO只是其中的一种状况,  如果我是byte[]然后存储的是一张照片呢?是一个文件呢?是一个xml呢?是军码呢?是莫斯密码呢?



**我觉得你只是在Spring web模块提供的扩展能力上进行了二次封装从而限制Spring web的扩展能力. 是的你是解决了当前issue的bug,  可是你有想过么你你究竟是增强Spring web的能力? 还是只是为了让自己的GitHub好看一点, 让自己在未来职业焕发光彩?** 

言语过激, 但这是事实, 我能看到一个很努力但是在耍小聪明孩子,希望你别去其他社区打广告了

**Comment by RovingSea** [comment]
> 

依次回复下吧：
- 首先这个转换器只针对JSON，如果是别的就让他保持原有格式传输就行。
- 在 Spring web 提供的扩展上封装这点是没错，但做法和目的都有专向性，不能因为达到A的功能而没做B的功能就说A缺乏限制性。
- Github作为一个讨论社区，Spring-Cloud-Alibaba的前辈们也标上了标签，我丝毫没有打广告的意思，并且我在公司和学校也调研过，都对此表示期待，我有兴趣做出来了，为什么会觉得我是在耍小聪明呢？你觉得我做的不好，我欢迎你讨论共建，如果你不喜欢，当然你可以划走，为什么会留下恶语呢？

**Comment by RovingSea** [comment]
> 请别再打开这个issue了!!!
> 
> org.springframework.http.converter.HttpMessageConverter的各个子类难道都要在你的ControllerResponseAdvice类中写上一遍又一遍的if else么? 这让我觉得无聊, IO只是其中的一种状况, 如果我是byte[]然后存储的是一张照片呢?是一个文件呢?是一个xml呢?是军码呢?是莫斯密码呢?
> 
> **我觉得你只是在Spring web模块提供的扩展能力上进行了二次封装从而限制Spring web的扩展能力. 是的你是解决了当前issue的bug, 可是你有想过么你你究竟是增强Spring web的能力? 还是只是为了让自己的GitHub好看一点, 让自己在未来职业焕发光彩?**
> 
> 言语过激, 但这是事实, 我能看到一个很努力但是在耍小聪明孩子,希望你别去其他社区打广告了

依次回复下吧：
- 首先这个转换器只针对JSON，如果是别的就让他保持原有格式传输就行。
- 在 Spring web 提供的扩展上封装这点是没错，但做法和目的都有专向性，不能因为达到A的功能而没做B的功能就说A缺乏限制性。
- Github作为一个讨论社区，Spring-Cloud-Alibaba的前辈们也标上了标签，我丝毫没有打广告的意思，并且我在公司和学校也调研过，都对此表示期待，我有兴趣做出来了，为什么会觉得我是在耍小聪明呢？你觉得我做的不好，我欢迎你讨论共建，如果你不喜欢，当然你可以划走，为什么会留下恶语呢？

**Comment by galaxy-sea** [comment]
我主动关闭issue, 此举说明我并不想在讨论这个问题, 已经保持我最大的克制了
